  repositories:
    - name: new-repo
      force_create: true
      template: template-repo
      description: description of the repo2
      # A URL with more information about the repository
      homepage: https://example.github.io/
      auto_init: true

      topics: github, probot, new-topic, another-topic, topic-12
      private: true
      has_issues: true 
      has_wiki: false
      has_downloads: true
      default_branch: main
      allow_squash_merge: true
      allow_merge_commit: true
      allow_rebase_merge: true
