repository: 
  # Name of the repo
  name: testseba
  force_create: true
  template_repo: template-repo
  description: description of the repo
  homepage: https://example.github.io/
    
  auto_init: true
  topics: 
  - github
  - safe-settings
  - new-topic
  - another-topic
  - topic-12
  
  private: false
  visibility: private
  default_branch: main
  gitignore_template: Node
  allow_squash_merge: true
  allow_merge_commit: false
